### ISSUE TITLE
License Info

### ISSUE THREAD

**Issue by amritcoder** [hiba1725/youtubeClone#1]
What's about license ?
Can i use this for commercial projects ?

**Comment by hiba1725** [comment]
Hello, the license has been updated. However, this was a class project and I do not advise you to use it for commercial purposes unless after you perform extensive testing.

**Comment by amritcoder** [comment]
I will use for commercial project after lots of modification in this script and beta testing. Is this allowed ?

**Comment by hiba1725** [comment]
Yes. Knock yourself out! :D

**Comment by amritcoder** [comment]
Thanks a lot ☺️
